# Generated by Django 3.2.8 on 2021-10-29 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateData', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('discovery', models.TextField(blank=True)),
                ('tired', models.TextField(blank=True)),
                ('dislike', models.TextField(blank=True)),
                ('happy', models.TextField(blank=True)),
                ('best', models.TextField(blank=True)),
                ('tomorrow', models.TextField(blank=True)),
                ('other', models.TextField(blank=True)),
                ('summarize', models.TextField(blank=True)),
                ('breakfast', models.ImageField(blank=True, null=True, upload_to='images/breakfast/%Y/%m/%d/%s/')),
                ('breakfastName', models.CharField(blank=True, max_length=30)),
                ('breakfastEvaluation', models.IntegerField(blank=True, default='0')),
                ('lunch', models.ImageField(blank=True, null=True, upload_to='images/lunch/%Y/%m/%d/%s/')),
                ('lunchName', models.CharField(blank=True, max_length=30)),
                ('lunchEvaluation', models.IntegerField(blank=True, default='0')),
                ('dinner', models.ImageField(blank=True, null=True, upload_to='images/dinner/%Y/%m/%d/%s/')),
                ('dinnerName', models.CharField(blank=True, max_length=30)),
                ('dinnerEvaluation', models.IntegerField(blank=True, default='0')),
                ('snack', models.ImageField(blank=True, null=True, upload_to='images/snack/%Y/%m/%d/%s/')),
                ('snackName', models.CharField(blank=True, max_length=30)),
                ('snackEvaluation', models.IntegerField(blank=True, default='0')),
                ('mealComment', models.TextField(blank=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
