# Generated by Django 3.2.8 on 2021-11-03 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memo',
            old_name='breakfastEvaluation',
            new_name='mealEvaluation',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='dinnerEvaluation',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='lunchEvaluation',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='snackEvaluation',
        ),
    ]
