# Generated by Django 3.2.8 on 2021-11-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211103_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='condition',
            field=models.CharField(blank=True, choices=[('good', '良好'), ('usually', '普通'), ('upset', '悪い')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='memo',
            name='mealEvaluation',
            field=models.CharField(blank=True, choices=[('vegetable', '野菜が少ない'), ('calorie', 'カロリーが高い'), ('nutrition', '栄養満点')], default='', max_length=30),
        ),
    ]
