# Generated by Django 3.2.8 on 2021-11-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211103_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='condition',
            field=models.CharField(blank=True, choices=[('良好', '良好'), ('普通', '普通'), ('悪い', '悪い')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='memo',
            name='mealEvaluation',
            field=models.CharField(blank=True, choices=[('野菜が少ない', '野菜が少ない'), ('カロリーが高い', 'カロリーが高い'), ('栄養満点', '栄養満点')], default='', max_length=30),
        ),
    ]
